{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}