{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "content-service.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}