apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: lomash-wood
  labels:
    app: analytics-service
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: lomash-wood-platform
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3008"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      protocol: TCP
      port: 3008
      targetPort: 3008
    - name: metrics
      protocol: TCP
      port: 9098
      targetPort: 3008