apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: lomash-wood-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: notification-service
          image: lomashwood/notification-service:dev
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: NODE_ENV
              value: development
            - name: LOG_LEVEL
              value: debug
            - name: EMAIL_PROVIDER
              value: nodemailer
            - name: SMS_PROVIDER
              value: mock
            - name: PUSH_PROVIDER
              value: mock
            - name: RETRY_MAX_ATTEMPTS
              value: "1"
            - name: FAILED_MESSAGE_RETRY_INTERVAL_MINUTES
              value: "60"