{{- if .Values.secrets.enabled }}
{{- if not .Values.secrets.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "product-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "product-service.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: REDIS_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: JWT_SECRET
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: S3_BUCKET_NAME
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: S3_BUCKET_NAME
    - secretKey: CDN_BASE_URL
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: CDN_BASE_URL
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: KAFKA_BROKERS
    - secretKey: KAFKA_CLIENT_ID
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: KAFKA_CLIENT_ID
    - secretKey: KAFKA_GROUP_ID
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: KAFKA_GROUP_ID
    - secretKey: SENTRY_DSN
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: SENTRY_DSN
    - secretKey: ELASTICSEARCH_URL
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/product-service
        property: ELASTICSEARCH_URL
{{- end }}
{{- end }}