apiVersion: v2
name: analytics-service
description: Lomash Wood Analytics Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - analytics
  - lomash-wood
  - microservice
maintainers:
  - name: Lomash Wood Platform Team
    email: platform@lomashwood.com
dependencies: []