apiVersion: v1
kind: Namespace
metadata:
  name: lomash-wood
  labels:
    app.kubernetes.io/name: lomash-wood
    app.kubernetes.io/part-of: lomash-wood-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: lomash-wood-staging
  labels:
    app.kubernetes.io/name: lomash-wood
    app.kubernetes.io/part-of: lomash-wood-platform
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: lomash-wood-dev
  labels:
    app.kubernetes.io/name: lomash-wood
    app.kubernetes.io/part-of: lomash-wood-platform
    environment: development