apiVersion: v1
kind: Service
metadata:
  name: {{ include "appointment-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "appointment-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.port }}