{{- if .Values.secrets.enabled }}
{{- if not .Values.secrets.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-payment-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-payment-service.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "order-payment-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "order-payment-service.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "order-payment-service.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: REDIS_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: JWT_SECRET
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: STRIPE_SECRET_KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: STRIPE_WEBHOOK_SECRET
    - secretKey: RAZORPAY_KEY_ID
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: RAZORPAY_KEY_ID
    - secretKey: RAZORPAY_KEY_SECRET
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: RAZORPAY_KEY_SECRET
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: KAFKA_BROKERS
    - secretKey: KAFKA_CLIENT_ID
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: KAFKA_CLIENT_ID
    - secretKey: KAFKA_GROUP_ID
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: KAFKA_GROUP_ID
    - secretKey: SENTRY_DSN
      remoteRef:
        key: lomash-wood/{{ .Values.configMap.data.NODE_ENV }}/order-payment-service
        property: SENTRY_DSN
{{- end }}
{{- end }}